### ISSUE TITLE
naming SimpleResult/SimpleError as Result/Error?

### ISSUE THREAD

**Issue by ChrisJefferson** [WiSaGaN/simple-error#3]
I notice lots of things in Rust define their types as Result/Error (for example io::Result uses io::Error in the standard library, and defines failure::Error).

**Comment by WiSaGaN** [comment]
Thanks for the report, Chris. This seems to be an idea worth exploring. I will revisit this when we release 0.2.0. Meanwhile you can always `use simple_error::SimpleError as Error`.

**Comment by WiSaGaN** [comment]
I think many error types that makes sense to just be `Error` are because they are errors in a specific domain, so an error type in websocket crate would be represented very nicely as `websocket::Error`. This crate though is more of an error type that is general, and it also stutters to say `simple_error::Error`. Without the crate though may confuse user with the `std::error::Error` trait.
